In [2]:
! pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.9.0-py3-none-any.whl (107 kB)
Requirement already satisfied: requests>=2.19.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (2.25.1)
Requirement already satisfied: pandas>=0.23 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (1.2.1)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader) (4.6.2)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas-datareader) (1.19.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2020.12.5)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.9.0

In [12]:
import pandas_datareader as web
from datetime import date
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [57]:
def get_dates(data_window):
    '''
    Returns the start date and end date for given number of years

    Parameters:
    data_window (int): number of years of past data

    Returns:
    start_date (datetime): start date
    end_date (datetime): today's date
    '''
    end_date = pd.to_datetime(date.today())
    start_date = pd.to_datetime(
        date.today() + relativedelta(years=-data_window))

    return start_date, end_date

In [58]:
data_window = 4 # look at last 4 years of data
start_date, end_date = get_dates(data_window)
stocks = ['AAPL', 'MSFT', 'AMZN', 'FB'] # top 4 SP500 stocks

In [82]:
# get stock data and store in CSV files

for stock in stocks:
    df = web.DataReader(stock, data_source='yahoo', start=start_date, end=end_date)
    df.to_csv('../data/{}.csv'.format(stock))

FileNotFoundError: [Errno 2] No such file or directory: '../data/AAPL.csv'

In [66]:
# take a look at the data
df.head()

Symbols,AAPL,MSFT,AMZN,FB,AAPL,MSFT,AMZN,FB,AAPL,MSFT,...,AMZN,FB,AAPL,MSFT,AMZN,FB,AAPL,MSFT,AMZN,FB
Attributes,Adj Close,Adj Close,Adj Close,Adj Close,Close,Close,Close,Close,High,High,...,Low,Low,Open,Open,Open,Open,Volume,Volume,Volume,Volume
Date,,,,,,,,,,,,,,,,,,,,,
2017-03-13,33.052044,60.897831,854.590027,139.600006,34.799999,64.709999,854.590027,139.600006,34.857498,65.190002,...,851.710022,138.669998,34.712502,65.010002,851.770020,138.710007,69686800.0,20100000.0,1909700.0,10955500.0
2017-03-14,33.002182,60.615509,852.530029,139.320007,34.747501,64.410004,852.530029,139.320007,34.912498,64.550003,...,847.549988,138.520004,34.825001,64.529999,853.549988,139.460007,61236400.0,14280200.0,2130600.0,12944000.0
2017-03-15,33.351227,60.935478,852.969971,139.720001,35.115002,64.750000,852.969971,139.720001,35.187500,64.919998,...,847.109985,138.490005,34.852501,64.550003,854.330017,139.289993,102767200.0,24833800.0,2562200.0,19344800.0
2017-03-16,33.405842,60.831951,853.419983,139.990005,35.172501,64.639999,853.419983,139.990005,35.255001,64.760002,...,850.510010,139.729996,35.180000,64.750000,855.299988,140.199997,76928000.0,20674300.0,1842300.0,13612900.0
2017-03-17,33.239635,61.048401,852.309998,139.839996,34.997501,64.870003,852.309998,139.839996,35.250000,65.239998,...,850.640015,139.699997,35.250000,64.910004,853.489990,140.339996,175540000.0,49219700.0,3384400.0,20592800.0

Symbols  Attributes  Date
AAPL     Adj Close   2017-03-13    3.305204e+01
                     2017-03-14    3.300218e+01
                     2017-03-15    3.335123e+01
                     2017-03-16    3.340584e+01
                     2017-03-17    3.323964e+01
                                       ...
FB       Volume      2021-03-05    2.680810e+07
                     2021-03-08    1.837270e+07
                     2021-03-09    2.201840e+07
                     2021-03-10    1.419750e+07
                     2021-03-11    1.528991e+07
Length: 24168, dtype: float64